CREATE OR REPLACE PACKAGE BODY JOB_APP_PKG AS

    PROCEDURE UPDATE_APPLICATION_STATUS(
        P_APPLICATION_ID NUMBER,
        P_NEW_STATUS VARCHAR2
    )
    IS
        V_STATUS VARCHAR2(50);
        V_VALID_APPLICATION_ID NUMBER;
        V_VALID_STATUS VARCHAR2(50);
    BEGIN
        V_VALID_APPLICATION_ID := VALIDATE_APPLICATION_ID(P_APPLICATION_ID);
        V_VALID_STATUS := VALIDATE_STATUS_ENTRY(P_NEW_STATUS);

        SELECT STATUS
        INTO V_STATUS
        FROM JOB_APPLICATIONS
        WHERE ID = V_VALID_APPLICATION_ID;

        IF V_STATUS != V_VALID_STATUS THEN

            INSERT INTO APPLICATION_HISTORY (
                APPLICATION_ID,
                OLD_STATUS,
                NEW_STATUS
            )
            VALUES (
                V_VALID_APPLICATION_ID,
                V_STATUS,
                V_VALID_STATUS
            );

        END IF;
    END UPDATE_APPLICATION_STATUS;

        RETURN P_NEW_STATUS;

    END VALIDATE_STATUS_ENTRY;

    FUNCTION VALIDATE_COMPANY_NAME(
        P_COMPANY_NAME VARCHAR2
    ) RETURN VARCHAR2
    IS
    BEGIN
        
        IF P_COMPANY_NAME IS NULL THEN
            RAISE_APPLICATION_ERROR(-20002, 'Company Must Have A Name');
        END IF;

        IF LENGTH(TRIM(P_COMPANY_NAME)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'Must Input A Longer Company Name');
        END IF;

        RETURN P_COMPANY_NAME;

    END VALIDATE_COMPANY_NAME;

    FUNCTION VALIDATE_ROLE_TITLE (
        P_ROLE_TITLE VARCHAR2
    ) RETURN VARCHAR2
    IS 
    BEGIN

        IF P_ROLE_TITLE IS NULL THEN
            RAISE_APPLICATION_ERROR(-20004, 'Must Have A Role Title');
        END IF;

        IF LENGTH(TRIM(P_ROLE_TITLE)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20005, 'Must Input A Longer Role Title');
        END IF;

        RETURN P_ROLE_TITLE;
    
    END VALIDATE_ROLE_TITLE;

    FUNCTION VALIDATE_APPLICATION_ID (
        P_APPLICATION_ID NUMBER
    ) RETURN NUMBER
    IS
    BEGIN
        
        IF P_APPLICATION_ID IS NULL THEN
            RAISE_APPLICATION_ERROR(-20006, 'Application ID is Required!');
        END IF;

        IF P_APPLICATION_ID <=0 THEN
            RAISE_APPLICATION_ERROR(-20007, 'Application ID Has to be Greater Than Zero');
        END IF;
    
        RETURN P_APPLICATION_ID;
    
    END VALIDATE_APPLICATION_ID;

    FUNCTION VALIDATE_DATE_APPLIED (
        P_DATE_APPLIED DATE
    ) RETURN DATE
    IS
    BEGIN

        IF P_DATE_APPLIED IS NULL THEN
            RAISE_APPLICATION_ERROR(-20008, 'A Date is Required!');
        END IF;

        IF P_DATE_APPLIED > SYSDATE THEN
            RAISE_APPLICATION_ERROR(-20009, 'Choose An Appropriate Date');
        END IF;

        RETURN P_DATE_APPLIED;
    
    END VALIDATE_DATE_APPLIED;

END JOB_APP_PKG;
/