CREATE OR REPLACE PACKAGE JOB_APP_PKG AS

    PROCEDURE UPDATE_APPLICATION_STATUS (
        P_APPLICATION_ID NUMBER,
        P_NEW_STATUS VARCHAR2
    );

    FUNCTION VALIDATE_STATUS_ENTRY (
        P_NEW_STATUS VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION VALIDATE_COMPANY_NAME (
        P_COMPANY_NAME VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION VALIDATE_ROLE_TITLE (
        P_ROLE_TITLE VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION VALIDATE_APPLICATION_ID (
        P_APPLICATION_ID NUMBER
    ) RETURN NUMBER;

    FUNCTION VALIDATE_DATE_APPLIED (
        P_DATE_APPLIED DATE
    ) RETURN DATE;

END JOB_APP_PKG;
/